version: '2.2'

services:

    api:
        cpus: 1
        mem_limit: 2G
        mem_reservation: 600m
        build: .
        environment:
            - RELOAD=--reload
            - PORT=5001
            - NUM_WORKERS=1
            - MPCONTRIBS_MONGO_HOST=$MPCONTRIBS_MONGO_HOST
        volumes:
            - .:/app
        ports:
            - "5001:5001"
